### PR TITLE
Vanilla CSS Status Indicator

### LINKED ISSUE #91: Rewrite ema status indicator in pure CSS
It is currently using Tailwind CSS. But if the user is not using Tailwind, the indicator styling would be broken!

Rewrite it to not depend on any CSS framework.

image

### PR DESCRIPTION
**Pull request by RiugaBachi**
:eyes:

Resolves #91 .

### CODE REVIEW

**Comment by srid** [comment]
@RiugaBachi Could you post a screenshot/video of how this looks on your browser/computer?

(We don't have to mirror the Tailwind style faithfully; so we have the creative freedom to change the indicator's styling; but since on my end the position of the indicator looks a bit off I wonder if we are facing a browser-specific difference).

**Comment by RiugaBachi** [comment]
image

**Comment by srid** [comment]
On Brave (a Chromium browser) as well as Safari it looks like this:

image

...

image

Hover tooltips does work, FWIW.

**Comment by srid** [comment]
I wonder if we can spot the precise difference by running the Tailwind CSS compiler on the current status indicator and then compare the generated styles with the one in this PR.

**Comment by RiugaBachi** [comment]
Could you see if that resolves the issue for you?

**Comment by srid** [comment]
@RiugaBachi It behaves the same, as in I see:

image

Are you not able to reproduce this locally in Chrome or Chromium?

**Comment by RiugaBachi** [comment]
Yea it appears as it does in [this](https://github.com/EmaApps/ema/pull/123#issuecomment-1193349217) comment for Vivaldi, Brave, Firefox on my system.

**Comment by srid** [comment]
So maybe this is a macOS-specific issue. Okay, I'll try to tweak this later. 

FTR, tailwind generates this CSS: https://gist.github.com/srid/2471813953a6df9b24909b9bb1d3cd2b#file-tailwind-compiled-css

**Comment by RiugaBachi** [comment]
Ok, I had a hunch and toyed around with measurements until I figured out it was `box-sizing: border-box`. This should definitely make it consistent across all resolutions.

Also apologies, I am a bit inept at frontend design lmao.

**Comment by srid** [comment]
Yup, that works (on Brave)!

> I am a bit inept at UI/UX lmao.

Most programmers are. :-) Tailwind is great for design for that reason.

**Pull request merged**
